config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root to: "lists#index"
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: [:destroy]

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie, presence: true
  validates :list, presence: true
  validates_uniqueness_of :list_id, :scope => [:movie_id]
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, uniqueness: true, presence: true

end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    @bookmark.save
    redirect_to list_path(@list)
  end

  # def create
  #   @review = Review.new(review_params)
  #   @review.restaurant = @restaurant
  #   @review.save
  #   redirect_to restaurant_path(@restaurant)
  # end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end



private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1> Add a bookmark/movie </h1>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container">
  <header>
    <h1 class="display-4 my-4">My Lists</h1>
  </header>

  <main>
    <ul class="list-group mb-4">
      <% @lists.each do |list| %>
        <li class="list-group-item">
          <%= link_to list.name, list_path(list), class: 'text-decoration-none' %>
        </li>
      <% end %>
    </ul>
  </main>

  <footer>
    <h5 class="mt-4">
      <%= link_to "Create a new list", new_list_path, class: 'btn btn-primary' %>
    </h5>
  </footer>
</div>

app/views/lists/new.html.erb
<h1> Create a new list</h1>

<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.input :movie_id %>
  <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<div class="container">
  <header class="my-4">
    <h1 class="display-4">Movies</h1>
  </header>

  <main>
    <% @list.bookmarks.each do |bookmark| %>
      <div class="card mb-4">
        <div class="row no-gutters">
          <div class="col-md-4">
            <img src="<%= bookmark.movie.poster_url %>" class="card-img" alt="<%= bookmark.movie.title %> poster">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title"><%= bookmark.movie.title %></h5>
              <p class="card-text"><%= bookmark.movie.overview %></p>
              <p class="card-text"><strong>Rating:</strong> <%= bookmark.movie.rating %></p>
              <p class="card-text"><strong>Comment:</strong> <%= bookmark.comment %></p>
              <%= link_to "Delete the movie", bookmark_path(bookmark), class: "btn btn-danger", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </main>

  <footer class="my-4">
    <div class="d-flex justify-content-between">
      <%= link_to "Add a movie", new_list_bookmark_path(@list), class: "btn btn-primary" %>
      <%= link_to "Go back", lists_path, class: "btn btn-secondary" %>
    </div>
  </footer>
</div>